apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ccmidterm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ccmidterm-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 20