apiVersion: v1
kind: Service
metadata:
  name: ccmidterm-service
  labels:
    app: ccmidterm-app
spec:
  type: NodePort
  selector:
    app: ccmidterm-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200